/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 3 Δεκ 2010, 3:53:04 πμ
 */

package superpear;
import java.util.*;
/**
 *
 * @author std07078
 */
public class CustomFrame extends javax.swing.JFrame {

    Db myDb;
    /** Creates new form NewJFrame */
    public CustomFrame() {
        //initMyComponents();
        initComponents();
    }
    public void setDb(Db db){
        myDb = db;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initMyComponents(){
        //myListModel = new javax.swing.DefaultListModel();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerInfoDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        userInfoTextArea = new javax.swing.JTextArea();
        userIconLabel = new javax.swing.JLabel();
        logLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList();
        playerInfoButton = new javax.swing.JButton();
        reapButton = new javax.swing.JButton();
        statButton = new javax.swing.JButton();
        ipLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        localIpLabel = new javax.swing.JLabel();

        playerInfoDialog.setTitle("Player Info");
        playerInfoDialog.setMinimumSize(new java.awt.Dimension(400, 400));

        userInfoTextArea.setColumns(20);
        userInfoTextArea.setFont(new java.awt.Font("Monospaced", 1, 14));
        userInfoTextArea.setRows(5);
        userInfoTextArea.setToolTipText("User Info Can Be Seen Here");
        jScrollPane2.setViewportView(userInfoTextArea);

        //userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userIcon.gif"))); // NOI18N
        userIconLabel.setText("USER INFO");

        javax.swing.GroupLayout playerInfoDialogLayout = new javax.swing.GroupLayout(playerInfoDialog.getContentPane());
        playerInfoDialog.getContentPane().setLayout(playerInfoDialogLayout);
        playerInfoDialogLayout.setHorizontalGroup(
            playerInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerInfoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        playerInfoDialogLayout.setVerticalGroup(
            playerInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerInfoDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(userIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Peer");
        setMinimumSize(new java.awt.Dimension(1000, 600));

        logLabel.setFont(new java.awt.Font("Courier New", 1, 12));
        logLabel.setText("Output Log");

        logTextArea.setBackground(new java.awt.Color(0, 0, 0));
        logTextArea.setColumns(20);
        logTextArea.setEditable(false);
        logTextArea.setFont(new java.awt.Font("Courier New", 0, 12));
        logTextArea.setForeground(new java.awt.Color(51, 204, 0));
        logTextArea.setRows(15);
        logTextArea.setToolTipText("The console output of the application");
        logTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        //logTextArea.setMinimumSize(new java.awt.Dimension(10,10));
        jScrollPane1.setViewportView(logTextArea);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 12));
        jLabel2.setText("Players");

        playerList.setBackground(new java.awt.Color(0, 0, 0));
        playerList.setFont(new java.awt.Font("Courier New", 0, 12));
        playerList.setForeground(new java.awt.Color(51, 204, 0));
        playerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        playerList.setToolTipText("select a player");
        jScrollPane3.setViewportView(playerList);

        playerInfoButton.setText("player info");
        playerInfoButton.setToolTipText("see player info");
        playerInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerInfoButtonMouseClicked(evt);
            }
        });
        playerInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerInfoButtonActionPerformed(evt);
            }
        });

        reapButton.setText("Reap");
        reapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reapButtonActionPerformed(evt);
            }
        });

         statButton.setText("Statistics");
        statButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButtonActionPerformed(evt);
            }
        });


        //jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/serverLogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ipLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(localIpLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playerInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localIpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerInfoButton)
                        .addGap(18, 18, 18)
                        .addComponent(reapButton)
                         .addGap(18, 18, 18)
                        .addComponent(statButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerInfoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerInfoButtonActionPerformed

    private void playerInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerInfoButtonMouseClicked
        // TODO add your handling code here:
        int index;
        index = playerList.getSelectedIndex();
        System.out.println(index);
        if(index != -1){
            userIconLabel.setText(myDb.getPlayer(index+1).getUsername());
            userInfoTextArea.setText("");
            userInfoTextArea.append("User Ip: "+myDb.getPlayer(index+1).getIp()+"\n");
            userInfoTextArea.append("User Id: "+myDb.getPlayer(index+1).id+"\n");
            userInfoTextArea.append("User Status: "+myDb.getPlayer(index+1).getStatus()+"\n\n");

            userInfoTextArea.setFont(new java.awt.Font("Courier New", 0, 12));
            userInfoTextArea.append("Statistics \n\n");
            userInfoTextArea.append("Wins: "+myDb.getPlayer(index+1).wins+"\n");
            userInfoTextArea.append("Ties: "+myDb.getPlayer(index+1).ties+"\n");
            userInfoTextArea.append("Losses: "+myDb.getPlayer(index+1).losses+"\n");



            playerInfoDialog.setVisible(true);
        }




    }//GEN-LAST:event_playerInfoButtonMouseClicked

    private void reapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reapButtonActionPerformed
        // TODO add your handling code here:
        this.logTextArea.append("Reaping Disconnected players..\n");
        myDb.reap();

    }

        private void statButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reapButtonActionPerformed
        // TODO add your handling code here:
        //this.logTextArea.append("..\n");

         System.out.println("Statistics called");
    //say sth!
    this.logTextArea.append("\n  Id|Games| W | T |  L | Per |Name\t|IP\n");
     Iterator vItr = SuperPeer.gamedb.players.iterator();
            while(vItr.hasNext()){
                Player temp = (Player) vItr.next();
               this.logTextArea.append("  "+temp.getId()+" ");
               // this.logTextArea.append(" "+temp.getIp()+"\t\t");
                this.logTextArea.append("   "+temp.getGames()+"         ");
                this.logTextArea.append(" "+temp.getWins()+" ");
                this.logTextArea.append(" "+temp.getTies()+" ");
                this.logTextArea.append(" "+temp.getLosses()+"  ");
                this.logTextArea.append("   "+temp.getPercentage()+" ");
                this.logTextArea.append("   "+temp.getUsername()+"\t");
                  this.logTextArea.append(" "+temp.getIp()+"\n");





    }
     this.logTextArea.append("\nOngoing Games\n");
        Iterator vItr2 = SuperPeer.gamedb.games.iterator();
            while(vItr2.hasNext()){
                Game temp = (Game) vItr2.next();
                   this.logTextArea.append("Game "+temp.getId()+": Peer "+temp.getPlayer1()+" vs Peer "+temp.getPlayer2());

            }





        //myDb.reap();

    }



    //GEN-LAST:event_reapButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ipLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel localIpLabel;
    public javax.swing.JLabel logLabel;
    public javax.swing.JTextArea logTextArea;
    private javax.swing.JButton playerInfoButton;
    public javax.swing.JDialog playerInfoDialog;
      public javax.swing.JDialog statDialog;
    public javax.swing.JList playerList;
    public javax.swing.JButton reapButton;
      public javax.swing.JButton statButton;
    public javax.swing.JLabel userIconLabel;
    public javax.swing.JTextArea userInfoTextArea;
    public javax.swing.JTextArea statTextArea;
    // End of variables declaration//GEN-END:variables

}
